- name: Install NodeJs
  hosts: all
  tasks:
    - name: Install nodejs package
      become_user: root
      ansible.builtin.apt:
        name:
          - nodejs
          - npm
        state: present