- hosts: all
  become: true
  tasks:
    - name: Pull client container
      shell: docker pull hawksdev/g1-yolo-client:1.0.1
      args:
        executable: /bin/bash

    - name: Pull backend container
      shell: docker pull hawksdev/g1-yolo-backend:1.0.1
      args:
        executable: /bin/bash
