steps:
  - id: "Deploy"
    name: bash
    args:
        [
         "curl",
         "-X POST",
         "https://api.render.com/deploy/srv-cfqrsipgp3joa8gevua0?key=2TNnrkN-rhA&ref=${COMMIT_SHA}"
        ]